apiVersion: v1
kind: Template
metadata:
  name: activation-keys
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: activation-keys
    spec:
      envName: ${ENV_NAME}
      title: "Manage Activation Keys"
      routePrefix: insights
      deploymentRepo: https://github.com/RedHatInsights/activation-keys-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/activation-keys
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - title: Remote Host Configuration
          expandable: true
          routes:
            - appId: connector
              title: Manage configuration
              href: /insights/connector
            - appId: activation-keys
              title: Activation Keys
              href: /insights/connector/activation-keys
      module:
        manifestLocation: /apps/activation-keys/fed-mods.json
        modules:
          - id: activation-keys
            module: ./RootApp
            routes:
              - pathname: /insights/connector/activation-keys
        moduleID: activation-keys
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/activation-keys-ui
