apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/activation-keys-ui?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/v1.20.0/pipelines/docker-build.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: activation-keys-ui
    appstudio.openshift.io/component: activation-keys-ui
    pipelines.appstudio.openshift.io/type: build
  name: activation-keys-ui-on-push
  namespace: teamnado-konflux-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/teamnado-konflux-tenant/activation-keys-ui/activation-keys-ui:{{revision}}
  - name: dockerfile
    value: ./build-tools/Dockerfile
  taskRunTemplate:
    serviceAccountName: build-pipeline-activation-keys-ui
  pipelineRef:
    name: docker-build
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
